version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: datummining_datum_1
      APP_PORT: 20000

  datum:
    image: ghcr.io/bugoao/datum_gateway:main@sha256:aee7b6172c8da3d621912aa4bc16a7e9d2f9ad7d27ec51fb5857a53f93b90a2d
    entrypoint: ["/app/datum_gateway"]
    command: ["--config=/app/conf/datum_gateway_config.json"]
    user: 1000:1000
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/settings/:/app/conf/
    ports:
      # datum gateway port
      - 23333:23334
